#!/bin/bash
# GreenOps Auto-Fix Script
# Fixes all critical errors in the greenops repository

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🔧 GreenOps Auto-Fix Script${NC}"
echo "===================================="
echo ""

# Check if we're in the right directory
if [ ! -f "README.md" ] || [ ! -d "agent" ]; then
    echo -e "${RED}❌ Error: Please run this script from the greenops directory${NC}"
    echo "Usage: cd ~/greenops && bash fix_all.sh"
    exit 1
fi

echo -e "${YELLOW}📋 Backing up current files...${NC}"
mkdir -p .backups
cp agent/requirements.txt .backups/agent_requirements.txt.bak 2>/dev/null || true
cp docker-compose.yml .backups/docker-compose.yml.bak 2>/dev/null || true

# Fix 1: Create correct agent requirements
echo -e "${GREEN}✓${NC} Fix #1: Creating correct agent/requirements.txt..."
cat > agent/requirements.txt << 'EOF'
# GreenOps Agent Dependencies
requests==2.31.0

# Optional: For advanced idle detection on Linux
# python-xlib==0.33  # Uncomment if needed
EOF

# Fix 2: Create missing __init__.py files
echo -e "${GREEN}✓${NC} Fix #2: Creating missing __init__.py files..."
touch server/__init__.py 2>/dev/null || true
touch server/routes/__init__.py 2>/dev/null || true
touch server/services/__init__.py 2>/dev/null || true
touch agent/__init__.py 2>/dev/null || true

# Fix 3: Generate secure credentials
echo -e "${GREEN}✓${NC} Fix #3: Generating secure credentials..."
if [ ! -f ".env" ]; then
    python3 << 'PYEOF'
import secrets
with open('.env', 'w') as f:
    f.write(f"# GreenOps Environment Configuration\n")
    f.write(f"# Generated by fix_all.sh\n\n")
    f.write(f"JWT_SECRET_KEY={secrets.token_urlsafe(32)}\n")
    f.write(f"POSTGRES_PASSWORD={secrets.token_urlsafe(32)}\n")
    f.write(f"\n# Update DATABASE_URL with the password above\n")
print("✓ .env file created")
PYEOF
else
    echo "  .env already exists, skipping..."
fi

# Fix 4: Update server/main.py for gunicorn
echo -e "${GREEN}✓${NC} Fix #4: Fixing gunicorn app reference..."
if ! grep -q "^app = create_app()" server/main.py; then
    # Add app = create_app() before if __name__
    sed -i.bak '/if __name__/i\
app = create_app()\
' server/main.py 2>/dev/null || sed -i '' '/if __name__/i\
app = create_app()\
' server/main.py
    echo "  Updated server/main.py"
else
    echo "  Already fixed, skipping..."
fi

# Fix 5: Fix Dockerfile.server
echo -e "${GREEN}✓${NC} Fix #5: Fixing Dockerfile.server..."
if grep -q "create_app()" Dockerfile.server; then
    sed -i.bak 's/server.main:create_app()/server.main:app/g' Dockerfile.server 2>/dev/null || \
    sed -i '' 's/server.main:create_app()/server.main:app/g' Dockerfile.server
    echo "  Updated Dockerfile.server"
else
    echo "  Already fixed, skipping..."
fi

# Fix 6: Update README (FastAPI -> Flask)
echo -e "${GREEN}✓${NC} Fix #6: Fixing README documentation..."
if grep -q "FastAPI" README.md; then
    sed -i.bak 's/FastAPI/Flask/g' README.md 2>/dev/null || \
    sed -i '' 's/FastAPI/Flask/g' README.md
    echo "  Updated README.md"
else
    echo "  Already fixed, skipping..."
fi

# Fix 7: Install xprintidle (Linux only)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo -e "${GREEN}✓${NC} Fix #7: Installing xprintidle (Linux idle detection)..."
    if command -v xprintidle &> /dev/null; then
        echo "  xprintidle already installed"
    else
        echo "  Attempting to install xprintidle..."
        sudo apt-get update -qq && sudo apt-get install -y xprintidle 2>/dev/null || \
        echo "  ${YELLOW}⚠${NC}  Could not install xprintidle (requires sudo). Agent will report 0 idle time."
    fi
else
    echo -e "${YELLOW}⚠${NC}  Fix #7: Skipping xprintidle (not Linux)"
fi

# Fix 8: Create startup script
echo -e "${GREEN}✓${NC} Fix #8: Creating startup scripts..."
cat > start_server.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting GreenOps Server..."
docker-compose up -d
echo ""
echo "⏳ Waiting for services to be ready..."
sleep 30
echo ""
echo "📊 Service Status:"
docker-compose ps
echo ""
echo "🔍 Testing server health..."
curl -s http://localhost:8000/health | python3 -m json.tool
echo ""
echo "✅ Server is ready!"
echo "   Dashboard: http://localhost"
echo "   Login: admin / admin123"
echo ""
EOF
chmod +x start_server.sh

cat > start_agent.sh << 'EOF'
#!/bin/bash
echo "🤖 Starting GreenOps Agent..."
cd agent
if [ ! -d "venv" ]; then
    echo "📦 Creating virtual environment..."
    python3 -m venv venv
fi
source venv/bin/activate
echo "📦 Installing dependencies..."
pip install -q -r requirements.txt
echo "🚀 Starting agent..."
python3 agent.py
EOF
chmod +x start_agent.sh

echo ""
echo "===================================="
echo -e "${GREEN}✅ Auto-fix complete!${NC}"
echo ""
echo "📦 Backups saved in .backups/"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""
echo "1️⃣  Start the server:"
echo "   ./start_server.sh"
echo ""
echo "2️⃣  In a new terminal, start the agent:"
echo "   ./start_agent.sh"
echo ""
echo "3️⃣  Access dashboard:"
echo "   http://localhost"
echo "   Login: admin / admin123"
echo ""
echo "===================================="
echo ""
